version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - debezium_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT  # Agregar protocolo para CONTROLLER
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Conexión a Zookeeper
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_LISTENER_MODE: "dev"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - debezium_network

  debezium-mariadb-connector:
    image: debezium/connect:2.0
    container_name: debezium-connector
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=dbz-configs
      - OFFSET_STORAGE_TOPIC=dbz-offsets
      - BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    networks:
      - debezium_network

  postgres:
    image: postgres:14-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: auto_db
    ports:
      - "5432:5432"
    networks:
      - debezium_network
    command: postgres -c wal_level=logical -c max_replication_slots=4 -c max_wal_senders=4 -c listen_addresses='*'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgresql:/docker-entrypoint-initdb.d  # Montar los scripts de PostgreSQL

  mariadb:
    image: mariadb:10.5
    container_name: mariadb-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: auto_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"
    networks:
      - debezium_network
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-scripts/mariadb:/docker-entrypoint-initdb.d  # Montar los scripts de MariaDB

  spring-app:
    build: .
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auto_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./logs:/logs  # Monta el directorio de logs del host en el contenedor
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - postgres
      - mariadb
    networks:
      - debezium_network

volumes:
  postgres_data:  # Definimos el volumen aquí para PostgreSQL
    driver: local  # Esto usa el driver local predeterminado, puedes cambiarlo si deseas usar otro driver
  mariadb_data:  # Definimos el volumen aquí para MariaDB
    driver: local  # Esto usa el driver local predeterminado, puedes cambiarlo si deseas usar otro driver

networks:
  debezium_network:
    driver: bridge
