version: '3.8'

services:
  # Servicio de API Gateway con Kong
  kong:
    image: kong:latest
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
    ports:
      - "8000:8000"  # Puerto para la API (Kong -> graphql_proyect)
      - "8443:8443"  # Puerto HTTPS
      - "8001:8001"  # Administraci칩n HTTP
      - "8444:8444"  # Administraci칩n HTTPS
    volumes:
      - ./gateway/kong.yml:/etc/kong/kong.yml  # Montamos la configuraci칩n de Kong
    depends_on:
      - graphql_project
    networks:
      - kong-network

  # Servicio del microservicio en Python (FastAPI)
  graphql_project:
    build:
      context: ./graphql_project # Ruta donde est치 el Dockerfile
      dockerfile: Dockerfile
    container_name: graphql_project
    restart: always
    ports:
      - "8002:8000"  # Exponer puerto interno 8000 en 8002 para pruebas directas
    networks:
      - kong-network

networks:
  kong-network:
    driver: bridge
